{% set name = "pyqg-jax" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyqg-jax-{{ version }}.tar.gz
  sha256: a1b83dc2b25686a44e8b8ca82b4e58808c93dc01312b58e661bbf91d26a9b95e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - flit-core >=3.2,<4
    - pip
  run:
    - python >=3.8
    - jax >=0.3.21
    - jaxtyping

test:
  imports:
    - pyqg_jax
  commands:
    - pip check
    - JAX_ENABLE_X64=True JAX_DEFAULT_DTYPE_BITS=32 pytest tests  # [unix]
  source_files:
    - tests
  requires:
    - pip
    - pyqg
    - pytest
    # Spurious dependency from PyQG (affects pip check)
    - cython
    # See issue conda-forge/pyfftw-feedstock#51
    - pyfftw <0.13

about:
  home: https://github.com/karlotness/pyqg-jax
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  description: |
    This is a partial port of PyQG to JAX which enables GPU
    acceleration, batching, automatic differentiation, etc.
  summary: Quasigeostrophic model in JAX (port of PyQG)
  doc_url: https://pyqg-jax.readthedocs.io/
  dev_url: https://github.com/karlotness/pyqg-jax

extra:
  recipe-maintainers:
    - karlotness
